//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actors_Perfomances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actors_Perfomances()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int Actors_PerfomancesID { get; set; }
        public Nullable<int> ActorID { get; set; }
        public Nullable<int> PerfomanceID { get; set; }
    
        public virtual Actors Actors { get; set; }
        public virtual Perfomances Perfomances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
