//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class TheaterEntities : DbContext
    {
        public TheaterEntities()
            : base("name=TheaterEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Actors> Actors { get; set; }
        public virtual DbSet<Actors_Perfomances> Actors_Perfomances { get; set; }
        public virtual DbSet<Audiences> Audiences { get; set; }
        public virtual DbSet<Directors> Directors { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Perfomances> Perfomances { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Scripts> Scripts { get; set; }
        public virtual DbSet<Theaters> Theaters { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }


    }
}