//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TicketID { get; set; }
        public Nullable<int> AudienceID { get; set; }
    
        public virtual Audiences Audiences { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
