//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfomances
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfomances()
        {
            this.Actors_Perfomances = new HashSet<Actors_Perfomances>();
            this.Scripts = new HashSet<Scripts>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int PerfomanceID { get; set; }
        public string Title { get; set; }
        public string Duration { get; set; }
        public string Genre { get; set; }
        public Nullable<int> TheaterID { get; set; }
        public Nullable<int> DirectorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actors_Perfomances> Actors_Perfomances { get; set; }
        public virtual Directors Directors { get; set; }
        public virtual Theaters Theaters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scripts> Scripts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        public DateTime DateOfStart { get; internal set; }
        public string TheaterName { get; internal set; }

    }
}
