//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public int RoleID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Actors_PerfomancesID { get; set; }
    
        public virtual Actors_Perfomances Actors_Perfomances { get; set; }
    }
}
