//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theater
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scripts
    {
        public int ScriptID { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public Nullable<int> PerfomanceID { get; set; }
    
        public virtual Perfomances Perfomances { get; set; }
    }
}
